doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                # configure these for your database server
                url: '%env(DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.6'
                charset: utf8

            mysql:
                # configure these for your database server
                url: '%env(DATABASE_MYSQL_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.6'
                charset: utf8
                mapping_types:
                    enum: string
                    set: string
                    varbinary: string
                    tinyblob: text

    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    WorldOfPonies:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/WorldOfPonies'
                        prefix: 'App\Entity\WorldOfPonies'
                        alias: WorldOfPonies
            mysql:
                connection: mysql
                mappings:
                    mysql:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Mysql'
                        prefix: 'App\Entity\Mysql'
                        alias: Mysql
