#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#delete:
#  pattern: worldofponies/player
#  defaults: { _controller: AcmePageBundle:InscritsManagement:ajaxMessageGroup}
